#
#  Makefile for the Linux Controller Area Network SPI drivers.
#


obj-$(CONFIG_CAN_HI311X)	+= hi311x.o
obj-$(CONFIG_CAN_MCP251X)	+= mcp251x.o
obj-$(CONFIG_CAN_MCP25XXFD) += mcp25xxfd.o
obj-$(CONFIG_CAN_TCAN4X5X)	+= tcan4x5x.o
obj-$(CONFIG_CAN_DBG_TCAN4X5X)	+= dbg_tcan4x5x.o
